### ISSUE TITLE
Extend templates

### ISSUE THREAD

**Issue by kappaj** [Prometee/SyliusVIESClientPlugin#8]
I have some problems extending the `@SyliusShop/Checkout/Address/_form.html.twig` Template. Because of the CompilerPass in `PrometeeSyliusVIESClientPlugin`, the common way to override templates is not working.
Is there an good way to override the form template without writing my own CompilerPass?

**Comment by Prometee** [comment]
Normally you just have to add a new twig file into `/templates/bundles/SyliusShopBundle/Checkout/Address/_form.html.twig` and it will be overrode.
The CompilerPass used into `PrometeeSyliusVIESClientPlugin` is just a quick way to override the Sylius base template letting the user override it into `/templates/bundles/*`.

The file your are mentioning is not used into this plugin maybe you forgot to `cache:clear` because the list of overrides are built during the `warmup`, so if you add or delete an overrode file you should clear the cache.

**Comment by kappaj** [comment]
Oh it was the wrong file. I mean `@SyliusShop/Common/Form/_address.html.twig`
I have a file in the `/templates/bundles/*` folder but after installing the plugin it is not recognized anymore.

**Comment by Prometee** [comment]
Let me retest it

**Comment by Prometee** [comment]
I have no easy way to avoid copying those templates overrides so I delete the `CompilerPass`, add a new section into the `README` to explain how to copy those overrides, and I move `src/Resources/views/overrides/*` one folder up.

New release is coming

**Comment by kappaj** [comment]
Good solution. Thank you!
